import './global.css';
import { CartProvider } from '@/lib/cart';

export const metadata = {
  title: 'Welcome to web-store',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
            {children}
        </CartProvider>
      </body>
    </html>
  );
}
