import './global.css';
import { CartProvider } from '@/lib/cart';

import { HeaderWithCart } from '@/components/layout/HeaderWithCart';
import { Footer } from '@/components/layout/Footer';

export const metadata = {
  title: 'Welcome to web-store',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <HeaderWithCart />
          <main className="min-h-screen">
            {children}
          </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}
